env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
mongo_uri: "mongodb://mongo:27017"
database: "mongo"
secret_jwt_key: rhifewh32yr7932yuyfew8ygf8g2fg
autoria_key: fake-autoria-key
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  iddle_timeout: 60s
redis:
  address: "redis:6379"
  password: some-secret-password
  db: 0
  cache_time: 5m

